import AppKit
import Foundation

/// The app-wide appearance Aero applies to its native interface and web views.
enum BrowserAppearance: String, CaseIterable {
    case system
    case light
    case dark

    var name: String {
        switch self {
        case .system: "System"
        case .light: "Light"
        case .dark: "Dark"
        }
    }
}

/// A search provider Aero can use for text entered in the address field.
enum SearchEngine: String, CaseIterable {
    case google
    case duckDuckGo
    case bing
    case brave

    var name: String {
        switch self {
        case .google: "Google"
        case .duckDuckGo: "DuckDuckGo"
        case .bing: "Bing"
        case .brave: "Brave Search"
        }
    }

    /// Builds the provider's search-result URL without interpolating unescaped input.
    func url(for query: String) -> URL {
        let address: String
        switch self {
        case .google: address = "https://www.google.com/search"
        case .duckDuckGo: address = "https://duckduckgo.com/"
        case .bing: address = "https://www.bing.com/search"
        case .brave: address = "https://search.brave.com/search"
        }
        var components = URLComponents(string: address)!
        components.queryItems = [URLQueryItem(name: "q", value: query)]
        return components.url!
    }

    /// Identifies result pages generated by this provider so Aero does not save searches in history.
    func owns(_ url: URL) -> Bool {
        let host = url.host?.lowercased() ?? ""
        switch self {
        case .google: return host.hasPrefix("www.google.") && url.path == "/search"
        case .duckDuckGo: return ["duckduckgo.com", "www.duckduckgo.com"].contains(host) && url.path == "/"
        case .bing: return host == "www.bing.com" && url.path == "/search"
        case .brave: return host == "search.brave.com" && url.path == "/search"
        }
    }
}

/// User-controlled browser behavior shared by the settings page, address field, and downloads.
enum BrowserSettings {
    private static let searchEngineKey = "SearchEngine"
    private static let downloadDirectoryKey = "DownloadDirectory"
    private static let appearanceKey = "Appearance"

    static var appearance: BrowserAppearance {
        get { BrowserAppearance(rawValue: UserDefaults.standard.string(forKey: appearanceKey) ?? "") ?? .system }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: appearanceKey)
            applyAppearance()
        }
    }

    /// Applies the saved appearance before Aero creates its first window.
    static func applyAppearance() {
        switch appearance {
        case .system: NSApp.appearance = nil
        case .light: NSApp.appearance = NSAppearance(named: .aqua)
        case .dark: NSApp.appearance = NSAppearance(named: .darkAqua)
        }
    }

    static var searchEngine: SearchEngine {
        get { SearchEngine(rawValue: UserDefaults.standard.string(forKey: searchEngineKey) ?? "") ?? .google }
        set { UserDefaults.standard.set(newValue.rawValue, forKey: searchEngineKey) }
    }

    static var downloadDirectory: URL {
        get {
            if let path = UserDefaults.standard.string(forKey: downloadDirectoryKey),
                FileManager.default.fileExists(atPath: path)
            {
                return URL(fileURLWithPath: path, isDirectory: true)
            }
            return FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask)[0]
        }
        set { UserDefaults.standard.set(newValue.standardizedFileURL.path, forKey: downloadDirectoryKey) }
    }

    static var isDefaultBrowser: Bool {
        guard let target = URL(string: "https://aero.invalid"),
            let handler = NSWorkspace.shared.urlForApplication(toOpen: target)
        else { return false }
        return handler.standardizedFileURL == Bundle.main.bundleURL.standardizedFileURL
    }
}
