import AppKit
import Foundation

/// The app-wide appearance Aero applies to its native interface and web views.
enum Appearance: String, CaseIterable {
    case system
    case light
    case dark

    var name: String {
        switch self {
        case .system: "System"
        case .light: "Light"
        case .dark: "Dark"
        }
    }
}

/// A search provider Aero can use for text entered in the address field.
enum SearchEngine: String, CaseIterable {
    case google
    case duckDuckGo
    case bing
    case brave

    var name: String {
        switch self {
        case .google: "Google"
        case .duckDuckGo: "DuckDuckGo"
        case .bing: "Bing"
        case .brave: "Brave Search"
        }
    }

    /// Builds the provider's search-result URL without interpolating unescaped input.
    func url(for query: String) -> URL {
        let address: String
        switch self {
        case .google: address = "https://www.google.com/search"
        case .duckDuckGo: address = "https://duckduckgo.com/"
        case .bing: address = "https://www.bing.com/search"
        case .brave: address = "https://search.brave.com/search"
        }
        var components = URLComponents(string: address)!
        components.queryItems = [URLQueryItem(name: "q", value: query)]
        components.percentEncodedQuery = components.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")
        return components.url!
    }

    /// Identifies result pages generated by this provider so Aero does not save searches in history.
    func owns(_ url: URL) -> Bool {
        let host = url.host?.lowercased() ?? ""
        switch self {
        case .google: return host.hasPrefix("www.google.") && url.path == "/search"
        case .duckDuckGo: return ["duckduckgo.com", "www.duckduckgo.com"].contains(host) && url.path == "/"
        case .bing: return host == "www.bing.com" && url.path == "/search"
        case .brave: return host == "search.brave.com" && url.path == "/search"
        }
    }
}

/// User-controlled browser behavior shared by the settings page, address field, and downloads.
enum Settings {
    private static let searchEngineKey = "SearchEngine"
    private static let downloadDirectoryKey = "DownloadDirectory"
    private static let downloadBookmarkKey = "DownloadDirectoryBookmark"
    private static var scopedDownloadDirectory: URL?
    static let zoomLevels = [75, 90, 100, 110, 125, 150, 175, 200]

    static var defaultZoom: Int {
        get {
            let value = UserDefaults.standard.integer(forKey: "DefaultPageZoom")
            return zoomLevels.contains(value) ? value : 100
        }
        set { if zoomLevels.contains(newValue) { UserDefaults.standard.set(newValue, forKey: "DefaultPageZoom") } }
    }

    /// Zero retains history until cleared, -1 disables recording, and positive values are days.
    static var historyDays: Int {
        get { UserDefaults.standard.integer(forKey: "HistoryRetentionDays") }
        set { UserDefaults.standard.set(newValue, forKey: "HistoryRetentionDays") }
    }

    static var restoresSession: Bool {
        get {
            if let mode = UserDefaults.standard.string(forKey: "StartupMode") { return mode == "restore" }
            return UserDefaults.standard.bool(forKey: "RestoreSession")
        }
        set {
            UserDefaults.standard.set(newValue, forKey: "RestoreSession")
            UserDefaults.standard.set(newValue ? "restore" : "blank", forKey: "StartupMode")
            if !newValue { SavedSession.clear() }
        }
    }

    static var asksDownloadDestination: Bool {
        get { UserDefaults.standard.bool(forKey: "AskDownloadDestination") }
        set { UserDefaults.standard.set(newValue, forKey: "AskDownloadDestination") }
    }

    static var startupMode: String {
        get { UserDefaults.standard.string(forKey: "StartupMode") ?? (restoresSession ? "restore" : "blank") }
        set {
            guard ["blank", "pages", "restore"].contains(newValue) else { return }
            UserDefaults.standard.set(newValue, forKey: "StartupMode")
            UserDefaults.standard.set(newValue == "restore", forKey: "RestoreSession")
            if newValue != "restore" { SavedSession.clear() }
        }
    }
    static var startupPages: [URL] {
        (UserDefaults.standard.stringArray(forKey: "StartupPages") ?? []).compactMap(URL.init(string:)).filter(AddressInput.isWeb)
    }
    static var sleepTabs: Bool { UserDefaults.standard.object(forKey: "SleepTabs") as? Bool ?? true }
    static var globalPrivacyControl: Bool {
        guard #available(macOS 27.0, *) else { return false }
        return UserDefaults.standard.object(forKey: "GlobalPrivacyControl") as? Bool ?? true
    }
    static var trackerBlocking: Bool { UserDefaults.standard.object(forKey: "TrackerBlocking") as? Bool ?? true }
    static var sleepMinutes: Int {
        let value = UserDefaults.standard.integer(forKey: "SleepMinutes")
        return [5, 15, 30, 60, 120].contains(value) ? value : 30
    }
    static var minimumFontSize: Double {
        let value = UserDefaults.standard.double(forKey: "MinimumFontSize")
        return [0, 9, 12, 14, 16, 18, 20].contains(value) ? value : 0
    }
    static var siteZooms: [String: Double] {
        (UserDefaults.standard.dictionary(forKey: "SiteZooms") as? [String: Double] ?? [:]).filter {
            $0.value.isFinite && (0.25...5).contains($0.value)
        }
    }

    /// Resets preferences while retaining the library, installed extensions and website decisions.
    static func resetPreferences() {
        let keys = [
            "Appearance", "ShowFavicons", "SearchEngine", "CustomSearchDefault", "DefaultPageZoom", "MinimumFontSize", "TabFocusesLinks",
            "PreferredLanguage", "AppleLanguages", "SleepTabs", "SleepMinutes", "NeverSleepSites", "Autoplay", "RemoteSuggestions",
            "StartupMode", "RestoreSession", "StartupPages", "HistoryRetentionDays", "HTTPSFirst", "FraudWarnings", "BlockCookies",
            "ExtensionArtwork", "AskDownloadDestination", "DownloadDirectory", "DownloadDirectoryBookmark",
        ]
        keys.forEach { UserDefaults.standard.removeObject(forKey: $0) }
        scopedDownloadDirectory?.stopAccessingSecurityScopedResource()
        scopedDownloadDirectory = nil
        SavedSession.clear()
        applyAppearance()
    }
    private static let appearanceKey = "Appearance"
    private static let faviconsKey = "ShowFavicons"

    static var appearance: Appearance {
        get { Appearance(rawValue: UserDefaults.standard.string(forKey: appearanceKey) ?? "") ?? .system }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: appearanceKey)
            applyAppearance()
        }
    }

    /// Applies the saved appearance before Aero creates its first window.
    static func applyAppearance() {
        switch appearance {
        case .system: NSApp.appearance = nil
        case .light: NSApp.appearance = NSAppearance(named: .aqua)
        case .dark: NSApp.appearance = NSAppearance(named: .darkAqua)
        }
    }

    /// Whether tabs and address suggestions show site icons. On until the user turns it off; while
    /// off, no icon is fetched either.
    static var showsFavicons: Bool {
        get { UserDefaults.standard.object(forKey: faviconsKey) as? Bool ?? true }
        set { UserDefaults.standard.set(newValue, forKey: faviconsKey) }
    }

    static var searchEngine: SearchEngine {
        get { SearchEngine(rawValue: UserDefaults.standard.string(forKey: searchEngineKey) ?? "") ?? .google }
        set { UserDefaults.standard.set(newValue.rawValue, forKey: searchEngineKey) }
    }

    static var downloadDirectory: URL {
        get {
            if let scopedDownloadDirectory { return scopedDownloadDirectory }
            if let data = UserDefaults.standard.data(forKey: downloadBookmarkKey) {
                var stale = false
                if let url = try? URL(resolvingBookmarkData: data, options: .withSecurityScope, bookmarkDataIsStale: &stale),
                    url.startAccessingSecurityScopedResource()
                {
                    scopedDownloadDirectory = url
                    if stale, let fresh = try? url.bookmarkData(options: .withSecurityScope) {
                        UserDefaults.standard.set(fresh, forKey: downloadBookmarkKey)
                    }
                    return url
                }
            }
            if let path = UserDefaults.standard.string(forKey: downloadDirectoryKey),
                FileManager.default.isWritableFile(atPath: path)
            {
                return URL(fileURLWithPath: path, isDirectory: true)
            }
            return FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask)[0]
        }
    }

    /// Keeps sandbox access to a folder selected through NSOpenPanel across browser launches.
    static func chooseDownloadDirectory(_ url: URL) throws {
        let accessed = url.startAccessingSecurityScopedResource()
        defer { if accessed { url.stopAccessingSecurityScopedResource() } }
        let bookmark = try url.bookmarkData(options: .withSecurityScope)
        scopedDownloadDirectory?.stopAccessingSecurityScopedResource()
        scopedDownloadDirectory = nil
        UserDefaults.standard.set(bookmark, forKey: downloadBookmarkKey)
        UserDefaults.standard.set(url.path, forKey: downloadDirectoryKey)
    }

    static var isDefaultBrowser: Bool {
        guard let target = URL(string: "https://aero.invalid"),
            let handler = NSWorkspace.shared.urlForApplication(toOpen: target)
        else { return false }
        return handler.standardizedFileURL == Bundle.main.bundleURL.standardizedFileURL
    }
}
